[package]
name = "mainui-game-picker"
version = "1.0.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
regex = "1.12.2"
serde_json = "1.0.145"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true
