cargo-features = ["panic-immediate-abort"]

[package]
name = "mainui-game-picker"
version = "1.2.2"
edition = "2024"

[dependencies]
rand = "0.9.2"
serde_json = "1.0.145"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'immediate-abort'
strip = true
